/bin/count shield.py
/bin/count core/monitor.py
/bin/count core/config/config.py
/bin/count core/config/vars.py
/bin/count core/fx/design.py
/bin/count core/fx/graph.py
/bin/count core/tools/connection.py
/bin/count core/tools/hardware.py
/bin/count core/tools/os.py
/bin/count core/utilities/term_control.
